version: "3"
services:
    monolith_app:
        build:
            context: .
            dockerfile: Dockerfile
        image: monolith_app
        ports:
            - "8045:9000" # Map your local port 8000 to the PHP-FPM container port 9000
        volumes:
            - .:/var/www # Mount the current directory to the container's working directory
        depends_on:
            - db
        networks:
            - app_network
    db:
        image: mysql:5.7
        container_name: database
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: monolith
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app_network
    nginx:
        image: nginx:latest
        ports:
            - "8000:80" # Map port 8000 on your host to port 80 on the Nginx container
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - monolith_app
        networks:
            - app_network

volumes:
    db_data:
networks:
    app_network:
        external: true
