version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: monolith_app
        ports:
            - "8045:9000" # Map your local port 8000 to the PHP-FPM container port 9000
        volumes:
            - .:/var/www # Mount the current directory to the container's working directory
        depends_on:
            - db
    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: my_secret_password
            MYSQL_DATABASE: my_database_name
            MYSQL_USER: my_database_user
            MYSQL_PASSWORD: my_database_password
        volumes:
            - db_data:/var/lib/mysql
    nginx:
        image: nginx:latest
        ports:
            - "8000:80" # Map port 8000 on your host to port 80 on the Nginx container
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

volumes:
    db_data:
